#include <stdio.h>

char *screens[] =
{
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X           XXXXXXXXXXXXXXXXX          X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                   X                  X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          X                           X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXX  XXXXXXXX          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          X    XXXXXXXXXXXXX          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          XXXXXXXXXXXXX    X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X    XXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXX                    X",
"X                    XXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X    X    X    X    X    X    X    X   X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXX   X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X   XXXXXXXXXXXXXX          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          XXXXXXXXXXXXXX   X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X   XXXXXXXXXXXXXX          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          XXXXXXXXXXXXXX   X          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X                   X                  X",
"X                   X                  X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X        X       X          X",
"X          X        X       X          X",
"X                   X                  X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          X                X          X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X     X      XXXXXXX      XXXXXXXX     X",
"X     X            X             X     X",
"X     X            X             X     X",
"X     X            X             X     X",
"X     X            X             X     X",
"X     X            X             X     X",
"X     XXXXXXX      XXXXXXX       X     X",
"X                                X     X",
"X                                X     X",
"X                                X     X",
"X                                X     X",
"X                                X     X",
"X                                X     X",
"X                         XXXXXXXX     X",
"X     XXXXXXX      X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  XXXXXXXXXXXXXXX     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X     XXXXXXXXXXXXXXXXX    X     X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                                      X",
"X                                      X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"X                X                     X",
"XXXXXXXXXXXXXXXXXX                     X",
"X                                      X",
"X                                      X",
"X                    XXXXXXXXXXXXXXXXXXX",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                                      X",
"X                                      X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXX     XXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"X                    X                 X",
"XXXXXXXXXXXXXXXXXXX  X                 X",
"X                                      X",
"X                                      X",
"X                 X  XXXXXXXXXXXXXXXXXXX",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"X                 X                    X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                                      X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"XXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXX",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                                      X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"X                  X                   X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X     XXXXXX      X  X      XXXXXX     X",
"X          X      X  X      X          X",
"X          X   XXXX  XXXX   X          X",
"X       X  X   X        X   X  X       X",
"X       X  X   X        X   X  X       X",
"X       X  X   X  XXXX  X   X  X       X",
"X       X                      X       X",
"X       X                      X       X",
"X       X           X          X       X",
"X       X  XXXXX    X   XXXXX  X       X",
"X       X  X        X       X  X       X",
"X       X  X        X       X  X       X",
"X     XXX  X        X       X  XXX     X",
"X     X    X        X       X    X     X",
"X     X    X   XXXXXXXXXX   X    X     X",
"X     X    X        X       X    X     X",
"X     X    X        X       X    X     X",
"X          X        X       X          X",
"X          X        X       X          X",
"X          XXXXX    X   XXXXX          X",
"X     X             X            X     X",
"X     X             X            X     X",
"X     X        X        X        X     X",
"X     X    X   X        X   X    X     X",
"X     XXXXXX   XXXXXXXXXX   XXXXXX     X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X     XXXXXXXXXXXXX  XXXXXXXXXXXXX     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X    XXXXXXXXXXXXXXXXXX    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                     X     X",
"X     X    X                     X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    X                X    X     X",
"X     X    XXXXXXXXXXXXXXXXXX    X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     X                          X     X",
"X     XXXXXXXXXXXXX  XXXXXXXXXXXXX     X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                   X                  X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X                    X        X",
"X        XXXXXXXXXX   XXXXXXXXX        X",
"X        X                    X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X        X          X         X        X",
"X                   X                  X",
"X          XXXXXXXXXXXXXXXXXX          X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                    X                 X",
"X                    X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X                    X",
"X                 X                    X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"X                 X  X                 X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    X",
"X       X                              X",
"X       X                              X",
"X    X  X  XXXXXXXXXXXXXXXXXXXXXXXX    X",
"X    X  X  X                           X",
"X    X  X  X                           X",
"X    X  X  X  XXXXXXXXXXXXXXXXXXXXX    X",
"X    X  X  X  X                        X",
"X    X  X  X  X                        X",
"X    X  X  X  X  XXXXXXXXXXXXXXXXXX    X",
"X    X  X  X  X  X                     X",
"X    X  X  X  X  X                     X",
"X    X  X  X  X  X  XXXXXXXXXXXXXXX    X",
"X    X  X  X  X  X  X                  X",
"X    X  X  X  X  X  X                  X",
"X    X  X  X  X  X  X  XXXXXXXXXXXX    X",
"X    X  X  X  X  X  X  X               X",
"X    X  X  X  X  X  X  X               X",
"X    X  X  X  X  X  X  X  XXXXXXXXX    X",
"X    X  X  X  X  X  X  X  X            X",
"X    X  X  X  X  X  X  X  X            X",
"X    X  X  X  X  X  X  X  X  XXXXXX    X",
"X    X  X  X  X  X  X  X  X  X         X",
"X    X  X  X  X  X  X  X  X  X         X",
"X    X  X  X  X  X  X  X  X  X         X",
"X    X  X  X  X  X  X  X  X  X  XXX    X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                           X  X       X",
"X                           X  X       X",
"X XXXXXXXX  XXXXXXXX XXXXXXXX  XXXXXXX X",
"X X      X  X      X X               X X",
"X X      X  X      X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X",
"X                                      X",
"X XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X               X X",
"X X                X X      X  X     X X",
"X X                X X      X  X     X X",
"X XXXXXXXX  XXXXXXXX XXXXXXXX  XXXXXXX X",
"X        X  X                          X",
"X        X  X      X                   X",
"X                  X                   X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X              X   X   X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X                X   X                 X",
"X              XXXXXXXXX               X",
"X                                      X",
"X              XXXXXXXXX               X",
"X                X   X                 X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X X X X X               X",
"X              X   X   X               X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X    XXXXXX X              X XXXXXX    X",
"X    X      X              X      X    X",
"X    X XXXXXX XXXXXXXXXXXX XXXXXX X    X",
"X    X X                        X X    X",
"X    X X XXXXXXXXXX  XXXXXXXXXX X X    X",
"X    X X X                    X X X    X",
"X      X X                    X X      X",
"X    XXX X                    X XXX    X",
"X        X                    X        X",
"X      X X                    X X      X",
"X      X X                    X X      X",
"X      X X                    X X      X",
"X      X                        X      X",
"X      X                        X      X",
"X      X X                    X X      X",
"X      X X                    X X      X",
"X      X X                    X X      X",
"X        X                    X        X",
"X    XXX X                    X XXX    X",
"X      X X                    X X      X",
"X    X X X                    X X X    X",
"X    X X XXXXXXXXXX  XXXXXXXXXX X X    X",
"X    X X                        X X    X",
"X    X XXXXXX XXXXXXXXXXXX XXXXXX X    X",
"X    X      X              X      X    X",
"X    XXXXXX X              X XXXXXX    X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                          X           X",
"X                          X           X",
"X                          X           X",
"X                          X      X    X",
"X                          X      X    X",
"X                          X      X    X",
"X                          XXXXXX X XXXX",
"X                                 X    X",
"X                          XXXXXXXXXXX X",
"X                          X           X",
"X                          X           X",
"X           XXXXXXXXXXXXX  X           X",
"X           X           X  X           X",
"X           X           X  X           X",
"X           X  XXXXXXX  X  X           X",
"X           X  X     X  X  X           X",
"X           X  X     X  X  X           X",
"X           X  X  X     X  X           X",
"X           X  X  X     X  X           X",
"X           X  X  XXXXXXX  X           X",
"X           X  X           X           X",
"X           X  X           X           X",
"X           X  XXXXXXXXXXXXX           X",
"X           X                          X",
"X           X                          X",
"X XXXXXXXXXXX                          X",
"X    X                                 X",
"XXXX X XXXXXX                          X",
"X    X      X                          X",
"X    X      X                          X",
"X    X      X                          X",
"X           X                          X",
"X           X                          X",
"X           X                          X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                X     X               X",
"X                X     X               X",
"X                X     X               X",
"X                XXXXXXX               X",
"X                                      X",
"X         XXXXXXXXXX XXXXXXXXX         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X                                      X",
"XXXXXXXXX X                  X XXXXXXXXX",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X         XXXXXX XXXXXX XXXXXX         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X         X                  X         X",
"X XXXXXXX X                  X XXXXXXX X",
"X       X X                  X X       X",
"X       X X                  X X       X",
"X       X                      X       X",
"X       X                      X       X",
"X       X       XXXX XXXX      X       X",
"X       X       X       X      X       X",
"X       X       X       X      X       X",
"X       X       X       X      X       X",
"X       XXXXXXXXX       XXXXXXXX       X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X XXXXXXXX                             X",
"X X                                    X",
"X X                                    X",
"X X                                    X",
"X X                                    X",
"X X                                    X",
"X XXXXXXXX  X  XXXX  X  X    X  XXXXXX X",
"X        X  X  X     X  X    X  X      X",
"X        X  X  X     X  X    X  X      X",
"X        X  X  X     X  X    X  XXXXXX X",
"X        X  X  X     X  X    X       X X",
"X        X  X  X     X  X    X       X X",
"X        X  X  X     X  X    X       X X",
"X XXXXXXXX  X  X     X  XXXXXX  XXXXXX X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"X                                      X",
"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
};

#define NUM_SCREENS		28
#define NUM_ROWS		36
#define NUM_CHARS		40
#define	MAX_LINES		40

enum
{
	VERTICAL,
	HORIZONTAL,
};

typedef struct tagLine
{
	int x, y, length, style;
} Line;

typedef int bool;
enum
{
	false,
	true,
};

Line	screenLines[NUM_SCREENS][MAX_LINES];
int		screenLineCount[NUM_SCREENS];

bool isInVertical(int screen, int row, int character)
{
	int lines, screenRow = row - (screen*NUM_ROWS);
	Line *aLine = screenLines[screen];
	
	for(lines = 0; lines < screenLineCount[screen]; ++lines, ++aLine)
	{
		if(aLine->style = VERTICAL)
		{
			if(aLine->x == character && aLine->y <= screenRow && aLine->y + aLine->length > screenRow)
				return true;
		}
	}
	
	return false;
}

bool isInHorizontal(int screen, int row, int character)
{
	int lines, screenRow = row - (screen*NUM_ROWS);
	Line *aLine = screenLines[screen];
	
	for(lines = 0; lines < screenLineCount[screen]; ++lines, ++aLine)
	{
		if(aLine->style = HORIZONTAL)
		{
			if(aLine->y == screenRow && aLine->x <= character && aLine->x + aLine->length > character)
				return true;
		}
	}
	
	return false;
}

bool addToHorizontal(int screen, int row, int character)
{
	Line *aLine;
	int length, x, line, screenRow = row - (screen*NUM_ROWS);
	
	length = 0;
	for(x = character;' ' != screens[row][x]; ++x)
		++length;
		
	if(1 >= length)
		return false;
		
	line = screenLineCount[screen];
	aLine = &(screenLines[screen][line]);
	aLine->x = character;
	aLine->y = screenRow;
	aLine->length = length;
	aLine->style = HORIZONTAL;
	++screenLineCount[screen];
	
	return true;
}

void addToVertical(int screen, int row, int character)
{
	Line *aLine;
	int length, y, line, screenRow = row - (screen*NUM_ROWS);
	
	length = 0;
	for(y = row;' ' != screens[y][character]; ++y)
		++length;
		
	line = screenLineCount[screen];
	aLine = &(screenLines[screen][line]);
	aLine->x = character;
	aLine->y = screenRow;
	aLine->length = length;
	aLine->style = VERTICAL;
	++screenLineCount[screen];
}

void buildLine(int screen, int row)
{
	int x;
	
	for(x = 1; x < (NUM_CHARS-1); ++x)
	{
		if(' ' != screens[row][x])
		{
			if(!isInVertical(screen, row, x))
				if(!isInHorizontal(screen, row, x))
					if(!addToHorizontal(screen, row, x))
						addToVertical(screen, row, x);
		}
	}
}

void dumpLines()
{
	int screen, line, x0, y0, x1, y1;
	
	for(screen = 0 ; screen < NUM_SCREENS; ++screen)
	{
		printf("screen%d[] = {\n", screen);
		for(line = 0; line < screenLineCount[screen]; ++line)
		{
			Line *aLine = &(screenLines[screen][line]);
			x0 = aLine->x;
			y0 = aLine->y;
			if(HORIZONTAL == aLine->style)
			{
				y1 = y0;
				x1 = x0 + aLine->length;
			}
			else
			{
				x1 = x0;
				y1 = y0 + aLine->length;
			}
			printf("\t{%2d, %2d %2d %2d}", x0, y0, x1, y1);
		}
		printf("};\n");
	}
}

int main()
{
	int screen, row, y;
	
	row = 0;
	for(screen = 0; screen < NUM_SCREENS ; ++screen)
	{
		for(y = 0; y < NUM_ROWS; ++y, ++row)
		{
			if(!y || (NUM_ROWS-1) == y)
				continue;
				
			buildLine(screen, row);
		}
	}
	
	dumpLines();
	
	return 0;
}
